"""empty message

Revision ID: cf65446eeeab
Revises: e90aee5859f4
Create Date: 2021-08-01 12:24:06.834645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf65446eeeab'
down_revision = 'e90aee5859f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pinshares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pin_id', sa.String(), nullable=False),
    sa.Column('shared_by', sa.String(), nullable=False),
    sa.Column('shared_to', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pinshares')
    # ### end Alembic commands ###
